"""Registry of callable CAD tools exposed over the bridge."""

from tools import sketch_edit, interference, sketch_support, features, inspection, sketch, state, editing, bodies, motion, admin, animation, animation_entities, animation_actions, jobs, design_management, core_design, design_assemblies, design_extended, design_structure, design_solids, design_sheet_metal

_TOOL_MAP = {
    'sketch_offset':sketch_edit.offset,
    'sketch_trim':sketch_edit.trim,
    'interference_check':interference.check,
    'inspect_motion':motion.inspect_motion,
    'jobs_list':jobs.list_jobs,
    'jobs_inspect':jobs.inspect,
    'jobs_cancel':jobs.cancel,
    'jobs_forget':jobs.forget,
    'list_sketches':sketch.list_sketches,
    'inspect_sketch':sketch.inspect_sketch,
    'rename_sketch':sketch.rename_sketch,
    'delete_sketch':sketch.delete_sketch,
    'design_diagnostics':design_management.diagnostics,
    'body_inspect':design_management.body_inspect,
    'body_rename':design_management.body_rename,
    'body_delete':design_management.body_delete,
    'parameter_create':design_management.parameter_create,
    'parameter_delete':design_management.parameter_delete,
    'feature_inspect':design_management.feature_inspect,
    'feature_rename':design_management.feature_rename,
    'feature_suppress':design_management.feature_suppress,
    'feature_unsuppress':design_management.feature_unsuppress,
    'feature_delete':design_management.feature_delete,
    'geometry_list':core_design.geometry_list,
    'arcs_add':core_design.arcs_add,
    'splines_add':core_design.splines_add,
    'points_add':core_design.points_add,
    'profiles_list':core_design.profiles_list,
    'project_geometry':sketch_support.project_geometry,
    'body_topology':sketch_support.body_topology,
    'lines_add':core_design.lines_add,
    'lines_edit':core_design.lines_edit,
    'circles_add':core_design.circles_add,
    'circles_edit':core_design.circles_edit,
    'rectangles_add':core_design.rectangles_add,
    'geometry_set_construction':core_design.geometry_set_construction,
    'geometry_set_fixed':core_design.geometry_set_fixed,
    'geometry_delete':core_design.geometry_delete,
    'constraints_list':core_design.constraints_list,
    'constraints_add':core_design.constraints_add,
    'constraints_delete':core_design.constraints_delete,
    'dimensions_list':core_design.dimensions_list,
    'dimensions_set':core_design.dimensions_set,
    'dimensions_delete':core_design.dimensions_delete,
    'components_list':design_assemblies.components_list,
    'components_inspect':design_assemblies.components_inspect,
    'components_create':design_assemblies.components_create,
    'components_rename':design_assemblies.components_rename,
    'components_delete':design_assemblies.components_delete,
    'occurrences_list':design_assemblies.occurrences_list,
    'occurrences_inspect':design_assemblies.occurrences_inspect,
    'occurrences_create':design_assemblies.occurrences_create,
    'occurrences_delete':design_assemblies.occurrences_delete,
    'occurrences_ground':design_assemblies.occurrences_ground,
    'occurrences_unground':design_assemblies.occurrences_unground,
    'occurrences_transform':design_assemblies.occurrences_transform,
    'assembly_joints_list':design_assemblies.joints_list,
    'assembly_joints_inspect':design_assemblies.joints_inspect,
    'assembly_joint_geometry_list':design_assemblies.joint_geometry_list,
    'assembly_joints_create':design_assemblies.joints_create,
    'assembly_joints_edit':design_assemblies.joints_edit,
    'assembly_joints_lock':design_assemblies.joints_lock,
    'assembly_joints_unlock':design_assemblies.joints_unlock,
    'assembly_joints_suppress':design_assemblies.joints_suppress,
    'assembly_joints_unsuppress':design_assemblies.joints_unsuppress,
    'assembly_joints_flip':design_assemblies.joints_flip,
    'assembly_joints_unflip':design_assemblies.joints_unflip,
    'assembly_joints_delete':design_assemblies.joints_delete,
    'assembly_joints_limits_set':design_assemblies.joints_limits_set,
    'assembly_joints_limits_clear':design_assemblies.joints_limits_clear,
    'extended_design_capabilities':design_extended.capabilities,
    'surfaces_list':design_extended.surfaces_list,
    'surfaces_inspect':design_extended.surfaces_inspect,
    'surfaces_patch':design_extended.surfaces_patch,
    'surfaces_stitch':design_extended.surfaces_stitch,
    'surfaces_thicken':design_extended.surfaces_thicken,
    'surfaces_delete':design_extended.surfaces_delete,
    'meshes_list':design_extended.meshes_list,
    'meshes_inspect':design_extended.meshes_inspect,
    'meshes_create_triangles':design_extended.meshes_create_triangles,
    'meshes_edit':design_extended.meshes_edit,
    'meshes_delete':design_extended.meshes_delete,
    'forms_list':design_extended.forms_list,
    'forms_inspect':design_extended.forms_inspect,
    'forms_create_tsm':design_extended.forms_create_tsm,
    'forms_rename':design_extended.forms_rename,
    'forms_delete':design_extended.forms_delete,
    'sheet_metal_rules_list':design_extended.sheet_metal_rules_list,
    'sheet_metal_rules_inspect':design_extended.sheet_metal_rules_inspect,
    'sheet_metal_rules_copy':design_extended.sheet_metal_rules_copy,
    'sheet_metal_rules_edit':design_extended.sheet_metal_rules_edit,
    'sheet_metal_rules_delete':design_extended.sheet_metal_rules_delete,
    'material_libraries':design_extended.material_libraries,
    'materials_list':design_extended.materials_list,
    'materials_inspect':design_extended.materials_inspect,
    'materials_copy':design_extended.materials_copy,
    'materials_edit':design_extended.materials_edit,
    'materials_delete':design_extended.materials_delete,
    'materials_apply':design_extended.materials_apply,
    'materials_clear_appearance':design_extended.materials_clear_appearance,
    'configurations_list':design_extended.configurations_list,
    'configurations_inspect':design_extended.configurations_inspect,
    'configurations_initialize':design_extended.configurations_initialize,
    'configurations_create':design_extended.configurations_create,
    'configurations_copy':design_extended.configurations_copy,
    'configurations_edit':design_extended.configurations_edit,
    'configurations_rename':design_extended.configurations_rename,
    'configurations_activate':design_extended.configurations_activate,
    'configurations_delete':design_extended.configurations_delete,
    'construction_list':design_structure.construction_list,
    'construction_inspect':design_structure.construction_inspect,
    'plane_create_offset':design_structure.plane_create_offset,
    'plane_create_midplane':design_structure.plane_create_midplane,
    'plane_create_three_points':design_structure.plane_create_three_points,
    'plane_create_angle':design_structure.plane_create_angle,
    'axis_create_two_points':design_structure.axis_create_two_points,
    'axis_create_two_planes':design_structure.axis_create_two_planes,
    'axis_create_edge':design_structure.axis_create_edge,
    'point_create_on_entity':design_structure.point_create_on_entity,
    'point_create_center':design_structure.point_create_center,
    'construction_rename':design_structure.construction_rename,
    'construction_show':design_structure.construction_show,
    'construction_hide':design_structure.construction_hide,
    'construction_set_parameter':design_structure.construction_set_parameter,
    'construction_delete':design_structure.construction_delete,
    'timeline_inspect':design_structure.timeline_inspect,
    'timeline_roll':design_structure.timeline_roll,
    'timeline_move_beginning':design_structure.timeline_move_beginning,
    'timeline_move_end':design_structure.timeline_move_end,
    'timeline_groups_list':design_structure.timeline_groups_list,
    'timeline_group_inspect':design_structure.timeline_group_inspect,
    'timeline_group_create':design_structure.timeline_group_create,
    'timeline_group_rename':design_structure.timeline_group_rename,
    'timeline_group_collapse':design_structure.timeline_group_collapse,
    'timeline_group_expand':design_structure.timeline_group_expand,
    'timeline_group_delete_keep':design_structure.timeline_group_delete_keep,
    'timeline_group_delete_contents':design_structure.timeline_group_delete_contents,
    'selection_clear':design_structure.selection_clear,
    'selection_add':design_structure.selection_add,
    'selection_remove':design_structure.selection_remove,
    'solid_features_capabilities':design_solids.capabilities,
    'solid_features_list':design_solids.solid_features_list,
    'solid_feature_inspect':design_solids.solid_feature_inspect,
    'solid_feature_edit':design_solids.solid_feature_edit,
    'solid_feature_delete':design_solids.solid_feature_delete,
    'holes_create':design_solids.holes_create,
    'shells_create':design_solids.shells_create,
    'drafts_create':design_solids.drafts_create,
    'mirrors_create':design_solids.mirrors_create,
    'lofts_create':design_solids.lofts_create,
    'sweeps_create':design_solids.sweeps_create,
    'sheet_metal_capabilities':design_sheet_metal.capabilities,
    'sheet_metal_inspect':design_sheet_metal.inspect,
    'sheet_metal_faces_list':design_sheet_metal.faces_list,
    'sheet_metal_rules_list_all':design_sheet_metal.rules_list,
    'sheet_metal_rule_assign':design_sheet_metal.rule_assign,
    'sheet_metal_component_create':design_sheet_metal.component_create,
    'sheet_metal_convert':design_sheet_metal.convert,
    'sheet_metal_features_list':design_sheet_metal.features_list,
    'sheet_metal_feature_inspect':design_sheet_metal.feature_inspect,
    'sheet_metal_feature_delete':design_sheet_metal.feature_delete,
    'sheet_metal_fold_create':design_sheet_metal.fold_create,
    'sheet_metal_fold_edit_angle':design_sheet_metal.fold_edit_angle,
    'sheet_metal_unfold_create':design_sheet_metal.unfold_create,
    'sheet_metal_unfold_edit':design_sheet_metal.unfold_edit,
    'sheet_metal_refold_create':design_sheet_metal.refold_create,
    'sheet_metal_flat_pattern_create':design_sheet_metal.flat_pattern_create,
    'sheet_metal_flat_pattern_inspect':design_sheet_metal.flat_pattern_inspect,
    'sheet_metal_flat_pattern_rename':design_sheet_metal.flat_pattern_rename,
    'sheet_metal_flat_pattern_delete':design_sheet_metal.flat_pattern_delete,
    "assembly_instances": motion.assembly_instances,
    "list_joints": motion.list_joints,
    "drive_joint": motion.drive,
    "open_animation": motion.open_preview,
    "check_animation": motion.check,
    "render_animation": motion.render,
    "list_bodies": bodies.list_bodies,
    "combine_bodies": bodies.combine_bodies,
    "list_parameters": editing.list_parameters,
    "edit_parameters": editing.edit_parameters,
    "list_timeline": design_structure.timeline_list,
    # state
    "get_state": state.get_state,
    # sketches
    "create_sketch": sketch.create_sketch,
    "add_circle": sketch.add_circle,
    "add_rectangle": sketch.add_rectangle,
    "add_line": sketch.add_line,
    "add_dimension": sketch.add_dimension,
    # features
    "extrude": features.extrude,
    "revolve": features.revolve,
    "fillet": features.fillet,
    "chamfer": features.chamfer,
    "circular_pattern": features.circular_pattern,
    "rectangular_pattern": features.rectangular_pattern,
    # inspection / management
    "measure_body": inspection.measure_body,
    "get_active_selection": inspection.get_active_selection,
    "screenshot_viewport": inspection.screenshot_viewport,
    "export_design": inspection.export_design,
    "list_features": design_management.features_list,
    "delete_features": inspection.delete_features,
    "reset_design": inspection.reset_design,
    "animation_components_list": animation_entities.list_components,
    "animation_component_inspect": animation_entities.inspect_component,
    "camera_inspect": animation.camera_inspect,
    "animation_playback_status": animation.playback_status,
    "animation_playback_full_screen": animation.playback_full_screen,
    "animation_camera_recording": animation.camera_recording,
    "animation_settings_inspect": animation.settings_inspect,
    "animation_settings_recording_mode": animation.settings_recording_mode,
    "animation_settings_watermark": animation.settings_watermark,
    "animation_authoring_capabilities": animation.authoring_capabilities,
    "animation_actions_rotate": animation_actions.rotate,
}

# Only explicitly registered handlers are callable; module helpers are private.
from bridge.commands import SPECS
for _handler, *_ in SPECS.values():
    if _handler not in _TOOL_MAP:
        _module = animation if _handler.startswith('storyboards_') else admin
        _TOOL_MAP[_handler] = getattr(_module, _handler)


def register_all(dispatcher):
    """Store the tool map so the HTTP bridge can dispatch by name."""
    from bridge import server

    server._state["tools"] = _TOOL_MAP
